// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1680856459);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1680856579);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1680856489);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1680705943);
user_pref("browser.search.region", "VN");
user_pref("calendar.caldav.googleResync", 1680705941);
user_pref("calendar.list.sortOrder", "2d7f06c2-17fd-4478-b5a3-5e35e0ae4659");
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.calendar-main-default", true);
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.calendar-main-in-composite", true);
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.disabled", true);
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.name", "Home");
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.type", "storage");
user_pref("calendar.registry.2d7f06c2-17fd-4478-b5a3-5e35e0ae4659.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Ho_Chi_Minh");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1680856439703");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1680878265);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230310165821");
user_pref("extensions.lastAppVersion", "102.9.0");
user_pref("extensions.lastPlatformVersion", "102.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"bfe57dd0-432f-4755-942b-d2e51cb27947\",\"google@search.mozilla.org\":\"5055405a-28c4-4bf6-ab8d-30f648eaa534\",\"ddg@search.mozilla.org\":\"8064fdad-6a1f-4d59-8a82-11b9d6d67477\",\"amazondotcom@search.mozilla.org\":\"de01b8e1-159a-43ae-aa2f-c22e44e74f7e\",\"wikipedia@search.mozilla.org\":\"7b2e62b5-7ac1-415c-9c66-a4697b150b67\",\"bing@search.mozilla.org\":\"44218da4-1ca2-4931-8663-d249d40199c7\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "1e96f623-12b4-43bb-98fc-a6080a72698");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.9.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("services.settings.clock_skew_seconds", -18762);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1680875340);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1680875340);
user_pref("services.settings.thunderbird.search-config.last_check", 1680875340);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1680875340);
user_pref("toolkit.telemetry.cachedClientID", "814054bc-cc2f-4104-a8b1-ba86358cd75c");
user_pref("toolkit.telemetry.previousBuildID", "20230310165821");
